//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraumaSoftware.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int Id { get; set; }
        public int Treatment_Id { get; set; }
        public Nullable<int> Benefit_Id { get; set; }
        public decimal Sum { get; set; }
    
        public virtual Benefit Benefit { get; set; }
        public virtual Treatment Treatment { get; set; }
    }
}
