//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TraumaSoftware.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TraumaCenterEntities : DbContext
    {
        private static TraumaCenterEntities _context;

        public TraumaCenterEntities()
            : base("name=TraumaCenterEntities")
        {
        }

        public static TraumaCenterEntities Context()
        {
            if (_context == null) { _context = new TraumaCenterEntities(); }
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Benefit> Benefit { get; set; }
        public virtual DbSet<Cabinet> Cabinet { get; set; }
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Department> Department { get; set; }
        public virtual DbSet<Medcard> Medcard { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Specification> Specification { get; set; }
        public virtual DbSet<Treater> Treater { get; set; }
        public virtual DbSet<Treatment> Treatment { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
